"""RBAC catalog: permissions and the six seeded system roles.

These are the source of truth for seeding. Custom per-tenant roles compose the same
permission codes. UI enforcement is convenience only — the API is the authority.
"""

from __future__ import annotations

# --- Permission codes (verb on resource) ---
PERMISSIONS: dict[str, str] = {
    "org:configure": "Configure organization settings, workflows, policies",
    "user:manage": "Create/manage users and role assignments",
    "role:manage": "Create/manage roles and permissions",
    "applicant:read": "View applicants",
    "applicant:manage": "Create/update applicants and financial profiles",
    "document:read": "View authorized applicant financial documents",
    "document:upload": "Upload applicant financial documents",
    "loan:create": "Create loan applications",
    "loan:read": "View loan applications",
    "loan:review": "Move loans through review stages",
    "loan:approve": "Approve or reject loans (within policy limits)",
    "loan:disburse": "Disburse approved loans",
    "loan:service": "Record repayments and manage active loan servicing",
    "risk:read": "View risk scores and assessments",
    "risk:override": "Override AI risk assessment with justification",
    "credit_score:read": "View credit scores",
    "default:read": "View default probability predictions",
    "explanation:read": "View AI (SHAP) explanations",
    "fraud:read": "View fraud alerts",
    "fraud:resolve": "Confirm or dismiss fraud alerts",
    "analytics:read": "View analytics dashboards",
    "report:export": "Generate and export reports",
    "audit:read": "View audit logs",
    "notification:read": "View and acknowledge notifications",
    "platform:admin": "Platform-wide administration across tenants",
}

# --- System roles → permission sets ---
ROLE_PERMISSIONS: dict[str, list[str]] = {
    "Applicant": [
        "applicant:read",
        "document:read",
        "document:upload",
        "loan:create",
        "loan:read",
        "notification:read",
    ],
    "Loan Officer": [
        "applicant:read",
        "applicant:manage",
        "document:read",
        "document:upload",
        "loan:create",
        "loan:read",
        "loan:review",
        "risk:read",
        "credit_score:read",
        "explanation:read",
        "fraud:read",
        "analytics:read",
        "notification:read",
    ],
    "Risk Analyst": [
        "applicant:read",
        "document:read",
        "loan:read",
        "loan:review",
        "risk:read",
        "risk:override",
        "credit_score:read",
        "default:read",
        "explanation:read",
        "fraud:read",
        "analytics:read",
        "notification:read",
    ],
    "Branch Manager": [
        "applicant:read",
        "document:read",
        "loan:read",
        "loan:review",
        "loan:approve",
        "loan:disburse",
        "loan:service",
        "risk:read",
        "credit_score:read",
        "default:read",
        "explanation:read",
        "fraud:read",
        "fraud:resolve",
        "analytics:read",
        "report:export",
        "notification:read",
    ],
    "Administrator": [
        "org:configure",
        "user:manage",
        "role:manage",
        "applicant:read",
        "applicant:manage",
        "document:read",
        "document:upload",
        "loan:read",
        "loan:review",
        "loan:approve",
        "loan:service",
        "risk:read",
        "credit_score:read",
        "default:read",
        "explanation:read",
        "fraud:read",
        "fraud:resolve",
        "analytics:read",
        "report:export",
        "audit:read",
        "notification:read",
    ],
    "Super Admin": list(PERMISSIONS.keys()),
}

SYSTEM_ROLES = list(ROLE_PERMISSIONS.keys())
