"""initial enterprise schema

Revision ID: 1bc1f3336299
Revises:
Create Date: 2026-07-22 00:15:25.332839
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "1bc1f3336299"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "model_versions",
        sa.Column("task", sa.String(length=40), nullable=False),
        sa.Column("algorithm", sa.String(length=60), nullable=False),
        sa.Column("version", sa.String(length=30), nullable=False),
        sa.Column("stage", sa.String(length=20), nullable=False),
        sa.Column("metrics", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("artifact_uri", sa.String(length=300), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "organizations",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("type", sa.String(length=30), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("nrb_license_no", sa.String(length=100), nullable=True),
        sa.Column("settings", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "permissions",
        sa.Column("code", sa.String(length=80), nullable=False),
        sa.Column("description", sa.String(length=200), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "audit_logs",
        sa.Column("actor_user_id", sa.UUID(), nullable=True),
        sa.Column("action", sa.String(length=120), nullable=False),
        sa.Column("entity_type", sa.String(length=80), nullable=True),
        sa.Column("entity_id", sa.UUID(), nullable=True),
        sa.Column("before", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("after", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("ip_address", sa.String(length=60), nullable=True),
        sa.Column("request_id", sa.String(length=60), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_logs_action"), "audit_logs", ["action"], unique=False)
    op.create_index(op.f("ix_audit_logs_created_at"), "audit_logs", ["created_at"], unique=False)
    op.create_index(
        op.f("ix_audit_logs_organization_id"), "audit_logs", ["organization_id"], unique=False
    )
    op.create_table(
        "branches",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("code", sa.String(length=30), nullable=False),
        sa.Column("address", sa.String(length=300), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_branches_organization_id"), "branches", ["organization_id"], unique=False
    )
    op.create_table(
        "loan_products",
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("min_amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("max_amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("min_tenor_months", sa.Integer(), nullable=False),
        sa.Column("max_tenor_months", sa.Integer(), nullable=False),
        sa.Column("interest_rate", sa.Numeric(precision=6, scale=3), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_loan_products_organization_id"), "loan_products", ["organization_id"], unique=False
    )
    op.create_table(
        "notifications",
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("channel", sa.String(length=20), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("is_read", sa.Boolean(), nullable=False),
        sa.Column("delivery_status", sa.String(length=20), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_notifications_organization_id"), "notifications", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_notifications_user_id"), "notifications", ["user_id"], unique=False)
    op.create_table(
        "roles",
        sa.Column("organization_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("is_system", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "name", name="uq_role_org_name"),
    )
    op.create_index(op.f("ix_roles_organization_id"), "roles", ["organization_id"], unique=False)
    op.create_table(
        "applicants",
        sa.Column("branch_id", sa.UUID(), nullable=True),
        sa.Column("full_name", sa.String(length=150), nullable=False),
        sa.Column("date_of_birth", sa.Date(), nullable=True),
        sa.Column("gender", sa.String(length=20), nullable=True),
        sa.Column("phone", sa.String(length=30), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("address", sa.String(length=300), nullable=True),
        sa.Column("is_self_employed", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["branch_id"], ["branches.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_applicants_organization_id"), "applicants", ["organization_id"], unique=False
    )
    op.create_table(
        "role_permissions",
        sa.Column("role_id", sa.UUID(), nullable=False),
        sa.Column("permission_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["permission_id"], ["permissions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["role_id"], ["roles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("role_id", "permission_id"),
    )
    op.create_table(
        "users",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("branch_id", sa.UUID(), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=150), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("mfa_enabled", sa.Boolean(), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["branch_id"], ["branches.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "email", name="uq_user_org_email"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=False)
    op.create_index(op.f("ix_users_organization_id"), "users", ["organization_id"], unique=False)
    op.create_table(
        "asset_records",
        sa.Column("applicant_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("category", sa.String(length=80), nullable=True),
        sa.Column("value", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["applicant_id"], ["applicants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_asset_records_applicant_id"), "asset_records", ["applicant_id"], unique=False
    )
    op.create_index(
        op.f("ix_asset_records_organization_id"), "asset_records", ["organization_id"], unique=False
    )
    op.create_table(
        "business_records",
        sa.Column("applicant_id", sa.UUID(), nullable=False),
        sa.Column("business_name", sa.String(length=200), nullable=True),
        sa.Column("business_type", sa.String(length=120), nullable=True),
        sa.Column("monthly_revenue", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("years_operating", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["applicant_id"], ["applicants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_business_records_applicant_id"), "business_records", ["applicant_id"], unique=False
    )
    op.create_index(
        op.f("ix_business_records_organization_id"),
        "business_records",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "employment_records",
        sa.Column("applicant_id", sa.UUID(), nullable=False),
        sa.Column("employer_name", sa.String(length=200), nullable=True),
        sa.Column("position", sa.String(length=120), nullable=True),
        sa.Column("monthly_income", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("employment_months", sa.Integer(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["applicant_id"], ["applicants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_employment_records_applicant_id"),
        "employment_records",
        ["applicant_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_employment_records_organization_id"),
        "employment_records",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "existing_loans",
        sa.Column("applicant_id", sa.UUID(), nullable=False),
        sa.Column("lender", sa.String(length=150), nullable=True),
        sa.Column("outstanding_amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("monthly_installment", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("is_delinquent", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["applicant_id"], ["applicants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_existing_loans_applicant_id"), "existing_loans", ["applicant_id"], unique=False
    )
    op.create_index(
        op.f("ix_existing_loans_organization_id"),
        "existing_loans",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "expense_records",
        sa.Column("applicant_id", sa.UUID(), nullable=False),
        sa.Column("category", sa.String(length=120), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("frequency", sa.String(length=30), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["applicant_id"], ["applicants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_expense_records_applicant_id"), "expense_records", ["applicant_id"], unique=False
    )
    op.create_index(
        op.f("ix_expense_records_organization_id"),
        "expense_records",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "financial_documents",
        sa.Column("applicant_id", sa.UUID(), nullable=False),
        sa.Column("doc_type", sa.String(length=80), nullable=False),
        sa.Column("storage_key", sa.String(length=300), nullable=False),
        sa.Column("checksum", sa.String(length=128), nullable=True),
        sa.Column("scan_status", sa.String(length=30), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["applicant_id"], ["applicants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_financial_documents_applicant_id"),
        "financial_documents",
        ["applicant_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_financial_documents_organization_id"),
        "financial_documents",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "income_records",
        sa.Column("applicant_id", sa.UUID(), nullable=False),
        sa.Column("source", sa.String(length=120), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("frequency", sa.String(length=30), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["applicant_id"], ["applicants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_income_records_applicant_id"), "income_records", ["applicant_id"], unique=False
    )
    op.create_index(
        op.f("ix_income_records_organization_id"),
        "income_records",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "kyc_records",
        sa.Column("applicant_id", sa.UUID(), nullable=False),
        sa.Column("national_id", sa.String(length=50), nullable=True),
        sa.Column("document_type", sa.String(length=50), nullable=True),
        sa.Column("verification_status", sa.String(length=30), nullable=False),
        sa.Column("is_simulated_verification", sa.Boolean(), nullable=False),
        sa.Column("extra", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["applicant_id"], ["applicants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_kyc_records_applicant_id"), "kyc_records", ["applicant_id"], unique=False
    )
    op.create_index(
        op.f("ix_kyc_records_organization_id"), "kyc_records", ["organization_id"], unique=False
    )
    op.create_table(
        "liability_records",
        sa.Column("applicant_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("outstanding_amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("monthly_payment", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["applicant_id"], ["applicants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_liability_records_applicant_id"),
        "liability_records",
        ["applicant_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_liability_records_organization_id"),
        "liability_records",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "loan_applications",
        sa.Column("branch_id", sa.UUID(), nullable=True),
        sa.Column("applicant_id", sa.UUID(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=True),
        sa.Column("reference_no", sa.String(length=40), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("tenor_months", sa.Integer(), nullable=False),
        sa.Column("purpose", sa.String(length=300), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["applicant_id"], ["applicants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["branch_id"], ["branches.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["product_id"], ["loan_products.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_loan_applications_applicant_id"),
        "loan_applications",
        ["applicant_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_loan_applications_organization_id"),
        "loan_applications",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_loan_applications_reference_no"),
        "loan_applications",
        ["reference_no"],
        unique=False,
    )
    op.create_index(
        op.f("ix_loan_applications_status"), "loan_applications", ["status"], unique=False
    )
    op.create_table(
        "refresh_tokens",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("jti", sa.String(length=64), nullable=False),
        sa.Column("token_hash", sa.String(length=255), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("replaced_by", sa.String(length=64), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("jti"),
    )
    op.create_index(op.f("ix_refresh_tokens_user_id"), "refresh_tokens", ["user_id"], unique=False)
    op.create_table(
        "transaction_records",
        sa.Column("applicant_id", sa.UUID(), nullable=False),
        sa.Column("source_type", sa.String(length=20), nullable=False),
        sa.Column("txn_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("description", sa.String(length=200), nullable=True),
        sa.Column("is_simulated", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["applicant_id"], ["applicants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_transaction_records_applicant_id"),
        "transaction_records",
        ["applicant_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_transaction_records_organization_id"),
        "transaction_records",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "user_roles",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("role_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["role_id"], ["roles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "role_id"),
    )
    op.create_table(
        "ai_explanations",
        sa.Column("loan_id", sa.UUID(), nullable=False),
        sa.Column("prediction_type", sa.String(length=40), nullable=False),
        sa.Column("shap_contributions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("narrative", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["loan_id"], ["loan_applications.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ai_explanations_loan_id"), "ai_explanations", ["loan_id"], unique=False
    )
    op.create_index(
        op.f("ix_ai_explanations_organization_id"),
        "ai_explanations",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "credit_scores",
        sa.Column("loan_id", sa.UUID(), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("subscores", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("model_version", sa.String(length=40), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["loan_id"], ["loan_applications.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_credit_scores_loan_id"), "credit_scores", ["loan_id"], unique=False)
    op.create_index(
        op.f("ix_credit_scores_organization_id"), "credit_scores", ["organization_id"], unique=False
    )
    op.create_table(
        "default_predictions",
        sa.Column("loan_id", sa.UUID(), nullable=False),
        sa.Column("probability", sa.Numeric(precision=6, scale=4), nullable=False),
        sa.Column("horizon_months", sa.Integer(), nullable=False),
        sa.Column("model_version", sa.String(length=40), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["loan_id"], ["loan_applications.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_default_predictions_loan_id"), "default_predictions", ["loan_id"], unique=False
    )
    op.create_index(
        op.f("ix_default_predictions_organization_id"),
        "default_predictions",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "fraud_alerts",
        sa.Column("loan_id", sa.UUID(), nullable=False),
        sa.Column("alert_type", sa.String(length=80), nullable=False),
        sa.Column("severity", sa.String(length=10), nullable=False),
        sa.Column("status", sa.String(length=15), nullable=False),
        sa.Column("reasons", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["loan_id"], ["loan_applications.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_fraud_alerts_loan_id"), "fraud_alerts", ["loan_id"], unique=False)
    op.create_index(
        op.f("ix_fraud_alerts_organization_id"), "fraud_alerts", ["organization_id"], unique=False
    )
    op.create_table(
        "loan_decisions",
        sa.Column("loan_id", sa.UUID(), nullable=False),
        sa.Column("decision", sa.String(length=30), nullable=False),
        sa.Column("decided_by", sa.UUID(), nullable=True),
        sa.Column("rationale", sa.Text(), nullable=True),
        sa.Column("conditions", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["loan_id"], ["loan_applications.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_loan_decisions_loan_id"), "loan_decisions", ["loan_id"], unique=False)
    op.create_index(
        op.f("ix_loan_decisions_organization_id"),
        "loan_decisions",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "loan_workflow_events",
        sa.Column("loan_id", sa.UUID(), nullable=False),
        sa.Column("from_status", sa.String(length=30), nullable=True),
        sa.Column("to_status", sa.String(length=30), nullable=False),
        sa.Column("actor_user_id", sa.UUID(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["loan_id"], ["loan_applications.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_loan_workflow_events_loan_id"), "loan_workflow_events", ["loan_id"], unique=False
    )
    op.create_index(
        op.f("ix_loan_workflow_events_organization_id"),
        "loan_workflow_events",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "risk_scores",
        sa.Column("loan_id", sa.UUID(), nullable=False),
        sa.Column("band", sa.String(length=10), nullable=False),
        sa.Column("probability", sa.Numeric(precision=6, scale=4), nullable=False),
        sa.Column("model_version", sa.String(length=40), nullable=True),
        sa.Column("feature_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["loan_id"], ["loan_applications.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_risk_scores_loan_id"), "risk_scores", ["loan_id"], unique=False)
    op.create_index(
        op.f("ix_risk_scores_organization_id"), "risk_scores", ["organization_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_risk_scores_organization_id"), table_name="risk_scores")
    op.drop_index(op.f("ix_risk_scores_loan_id"), table_name="risk_scores")
    op.drop_table("risk_scores")
    op.drop_index(
        op.f("ix_loan_workflow_events_organization_id"), table_name="loan_workflow_events"
    )
    op.drop_index(op.f("ix_loan_workflow_events_loan_id"), table_name="loan_workflow_events")
    op.drop_table("loan_workflow_events")
    op.drop_index(op.f("ix_loan_decisions_organization_id"), table_name="loan_decisions")
    op.drop_index(op.f("ix_loan_decisions_loan_id"), table_name="loan_decisions")
    op.drop_table("loan_decisions")
    op.drop_index(op.f("ix_fraud_alerts_organization_id"), table_name="fraud_alerts")
    op.drop_index(op.f("ix_fraud_alerts_loan_id"), table_name="fraud_alerts")
    op.drop_table("fraud_alerts")
    op.drop_index(op.f("ix_default_predictions_organization_id"), table_name="default_predictions")
    op.drop_index(op.f("ix_default_predictions_loan_id"), table_name="default_predictions")
    op.drop_table("default_predictions")
    op.drop_index(op.f("ix_credit_scores_organization_id"), table_name="credit_scores")
    op.drop_index(op.f("ix_credit_scores_loan_id"), table_name="credit_scores")
    op.drop_table("credit_scores")
    op.drop_index(op.f("ix_ai_explanations_organization_id"), table_name="ai_explanations")
    op.drop_index(op.f("ix_ai_explanations_loan_id"), table_name="ai_explanations")
    op.drop_table("ai_explanations")
    op.drop_table("user_roles")
    op.drop_index(op.f("ix_transaction_records_organization_id"), table_name="transaction_records")
    op.drop_index(op.f("ix_transaction_records_applicant_id"), table_name="transaction_records")
    op.drop_table("transaction_records")
    op.drop_index(op.f("ix_refresh_tokens_user_id"), table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    op.drop_index(op.f("ix_loan_applications_status"), table_name="loan_applications")
    op.drop_index(op.f("ix_loan_applications_reference_no"), table_name="loan_applications")
    op.drop_index(op.f("ix_loan_applications_organization_id"), table_name="loan_applications")
    op.drop_index(op.f("ix_loan_applications_applicant_id"), table_name="loan_applications")
    op.drop_table("loan_applications")
    op.drop_index(op.f("ix_liability_records_organization_id"), table_name="liability_records")
    op.drop_index(op.f("ix_liability_records_applicant_id"), table_name="liability_records")
    op.drop_table("liability_records")
    op.drop_index(op.f("ix_kyc_records_organization_id"), table_name="kyc_records")
    op.drop_index(op.f("ix_kyc_records_applicant_id"), table_name="kyc_records")
    op.drop_table("kyc_records")
    op.drop_index(op.f("ix_income_records_organization_id"), table_name="income_records")
    op.drop_index(op.f("ix_income_records_applicant_id"), table_name="income_records")
    op.drop_table("income_records")
    op.drop_index(op.f("ix_financial_documents_organization_id"), table_name="financial_documents")
    op.drop_index(op.f("ix_financial_documents_applicant_id"), table_name="financial_documents")
    op.drop_table("financial_documents")
    op.drop_index(op.f("ix_expense_records_organization_id"), table_name="expense_records")
    op.drop_index(op.f("ix_expense_records_applicant_id"), table_name="expense_records")
    op.drop_table("expense_records")
    op.drop_index(op.f("ix_existing_loans_organization_id"), table_name="existing_loans")
    op.drop_index(op.f("ix_existing_loans_applicant_id"), table_name="existing_loans")
    op.drop_table("existing_loans")
    op.drop_index(op.f("ix_employment_records_organization_id"), table_name="employment_records")
    op.drop_index(op.f("ix_employment_records_applicant_id"), table_name="employment_records")
    op.drop_table("employment_records")
    op.drop_index(op.f("ix_business_records_organization_id"), table_name="business_records")
    op.drop_index(op.f("ix_business_records_applicant_id"), table_name="business_records")
    op.drop_table("business_records")
    op.drop_index(op.f("ix_asset_records_organization_id"), table_name="asset_records")
    op.drop_index(op.f("ix_asset_records_applicant_id"), table_name="asset_records")
    op.drop_table("asset_records")
    op.drop_index(op.f("ix_users_organization_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_table("role_permissions")
    op.drop_index(op.f("ix_applicants_organization_id"), table_name="applicants")
    op.drop_table("applicants")
    op.drop_index(op.f("ix_roles_organization_id"), table_name="roles")
    op.drop_table("roles")
    op.drop_index(op.f("ix_notifications_user_id"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_organization_id"), table_name="notifications")
    op.drop_table("notifications")
    op.drop_index(op.f("ix_loan_products_organization_id"), table_name="loan_products")
    op.drop_table("loan_products")
    op.drop_index(op.f("ix_branches_organization_id"), table_name="branches")
    op.drop_table("branches")
    op.drop_index(op.f("ix_audit_logs_organization_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_created_at"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_action"), table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_table("permissions")
    op.drop_table("organizations")
    op.drop_table("model_versions")
    # ### end Alembic commands ###
